### PR TITLE
fix problem with listeners not being passed to the styled component

### PR DESCRIPTION
**Pull request by pedrokermitgoncalves**
I was having a problem when extending Vuetify components. The listeners that already existed on the original Vue Component (i.e. onmouseenter) weren't being passed to the new component originated by  vue-styled-component.

This, merge request fixes that problem by passing the $listeners object to the new component, as it was already being done with the $props object.

### CODE REVIEW

**Comment by bornes** [comment]
Would like to see this get merged soon. This is really helpful

**Comment by liqueflies** [comment]
Use tag 1.4.5

**Comment by pedrokermitgoncalves** [comment]
Cool. that's quick!
Thanks man.

**Comment by pedrokermitgoncalves** [comment]
Hey @liqueflies can you please check if you properly publish the new tag to npm? i'm only able to install up to `1.4.4`

https://i.imgur.com/gcQb9gY.png

**Comment by pedrokermitgoncalves** [comment]
> Hey @liqueflies can you please check if you properly publish the new tag to npm? i'm only able to install up to `1.4.4`
> 
> https://i.imgur.com/gcQb9gY.png

Sorry about this. It was a problem on our private npm proxy.

**Comment by liqueflies** [comment]
Sounds strage...

https://www.npmjs.com/package/vue-styled-components

1.4.5 is published and if I type `npm i vue-styled-components` output command is:

`+ vue-styled-components@1.4.5`

**Comment by pedrokermitgoncalves** [comment]
@liqueflies yes, you're absolutely correct. This was a cached package on our private npm nexus machines

**Pull request merged**
