### PR TITLE
Implement attributes parameter while creating a styled component

### PR DESCRIPTION
**Pull request by m-sebastiyan**
This is the first implementation that supports only a plain object that describes attrs. #68 

```JSX
import styled from 'vue-styled-components';
const StyledImage = styled('img', {}, { src: 'image.jpg', alt: 'Test image' })`
  width: 50px;
  height: 50px;
`;
export default StyledImage;
```

I'm planning to extend it similarly to the original styled components (having an attr key that takes a function):

```JSX
const Input = styled.input.attrs(props => ({
  type: 'text',
  size: props.small ? 5 : undefined,
}))`
  border-radius: 3px;
  border: 1px solid palevioletred;
  display: block;
  margin: 0 0 1em;
  padding: ${props => props.padding};

  ::placeholder {
    color: palevioletred;
  }
`
```

### CODE REVIEW

**Comment by cheeks** [comment]
@liqueflies will this be merged in soon? Thanks

**Comment by PMK** [comment]
> @liqueflies will this be merged in soon? Thanks

Same here. Thanks

**Comment by the-rebirth-project** [comment]
@liqueflies Any chance of this being merged?

**Comment by liqueflies** [comment]
Hello everyone,
hello @m-sebastiyan, and thank you for PR's!

This is basically correct, just try to do two things: 

1. Follow the main library pattern: you added a new parameter to the styled function, in the main library they passed to options and then statically added to constructor (https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/constructors/constructWithOptions.js).
Rest of code is good.

2. Just rebase your branch with the new one and then we can check for merge :)

**Comment by liqueflies** [comment]
Solved merging  #111

**Pull request closed without merging**
